version: "3.8"
services:
  postgres:
    image: postgres:12
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data:cached

  redis:
    image: redis
    restart: always
    expose:
      - 6379

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa
      REDIS_URL: redis://redis
      NODE_ENV: development
      JWT_SECRET: some_jwt_secret
      COOKIE_SECRET: some_cookie_secret
      PORT: 9000
      STORE_CORS: /http://.+/
      ADMIN_CORS: /http://.+/
      AUTH_CORS: /http://.+/
    ports:
      - "9000:9000"
      - "7001:7001"
    command: yarn dev
    volumes:
      - ./backend/uploads:/app/uploads

  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development

volumes:
  app-db-data: